algoritmo "Calcula Media"
// Função :calcular a notas de duas provas
// Autor :Breno Miguel
// Data : 26/04/2022
// Seção de Declarações 
var
P1,P2,MEDIA:real

inicio
// Dados de Entrada
escreval("Entre com um valor para P1: ")
leia(P1)
escreval("Entre com um valor para P2: ")
leia(P2)
//Fim dos dados de entrada
//Processamento
MEDIA <- (P1+P2)/2
//daos nde saída
escreval("A Media do aluno é: ",MEDIA)
//fim dos dados de processamento
fimalgoritmo
