algoritmo "volei"
// Função :
// Autor :
// Data : 02/08/2022
// Seção de Declarações 
var
idade,altura,fim:real
inicio
// Seção de Comandos 
escreval("Informe sua idade")
leia(idade)
escreval("Informe sua altura")
leia(altura)
se (altura>=1.75) entao
   se (idade>=18) entao
      escreval("pode competir")
      
   senao
   escreval("não pode competir")
fimse
fimse
fimalgoritmo
