algoritmo "semnome"
// Função :
// Autor :
// Data : 23/08/2022
// Seção de Declarações 
var
contador,numero,soma,qtde:inteiro
media:real
inicio
// Seção de Comandos 
para contador de 1 ate 500 faca
 escreval("Digite um número: ")
 leia(numero)
 se (numero mod 2 = 0) entao
  soma <- soma+numero
  qtde <- qtde + 1
 fimse
 

fimpara
 escreval ("A soma é:", soma)
 escreval("Achei ",qtde," de pares")
// media<-soma/5
// escreval("Média é:",media)



fimalgoritmo
