algoritmo "semnome"
// Função :
// Autor :
// Data : 16/08/2022
// Seção de Declarações 
var
time:caracter
inicio
escreval("Escreva seu time")
leia(time)
escolha time
 caso "Palmeiras","São Paulo","Corinthians","Santos"
  escreval("Seu time é do eixo de Paulista")
 caso "Botafogo","Flamengo","Vasco","Fluminense"
  escreval("Seu time é um Carioca")
 outrocaso
  escreval("INVÁLIDO")
fimescolha
fimalgoritmo
