algoritmo "semnome"
// Função :
// Autor :
// Data : 21/06/2022
// Seção de Declarações 
var
idade, habilitacao, verificacao:logico
inicio
// Seção de Comandos 
escreval("escreva se é verdade se é maior que 18: ")
leia(idade)
escreval("escreva se é verdade se tem a carteira de motorista: ")
leia(habilitacao)
verificacao <- idade e habilitacao
escreval("Você pode dirigir? ", verificacao)




fimalgoritmo
